{
	"errors": {
		"WRONG_CONNECTION": "Can not connect to MonStor instance"
	}
}